// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"git.cie.com/ips/wire-provider/grpc/provider"
	"github.com/RyuChk/ips-map-service/cmd/map-grpc/internal/handler"
	"github.com/RyuChk/ips-map-service/cmd/map-grpc/server"
	"github.com/RyuChk/ips-map-service/internal/di"
	"github.com/google/wire"
)

// Injectors from di.go:

func InitializeContainer() (*Container, func(), error) {
	mapServiceServer := handler.ProvideMapServer()
	handlers := &handler.Handlers{
		Map: mapServiceServer,
	}
	grpcServerCustomizer := server.ProvideGRPCServerCustomizer(handlers)
	grpcServer, cleanup, err := provider.ProvideGRPCServer(grpcServerCustomizer)
	if err != nil {
		return nil, nil, err
	}
	container := &Container{
		server: grpcServer,
	}
	return container, func() {
		cleanup()
	}, nil
}

// di.go:

var BaseBindingSet = wire.NewSet(di.DatabaseSet, di.ConfigSet, di.ProviderSet)

var MainBindingSet = wire.NewSet(
	ProviderSet,
	BaseBindingSet, provider.WireSet, wire.Struct(new(Container), "*"),
)
